name: dartemis_addons
version: 0.1.0
author: david bernard
description: A set of addons (Component, System, helper, ...) usable with dartemis
homepage: https://github.com/davidB/dartemis_addons
documentation: https://github.com/davidB/dartemis_addons
dependencies:
  dartemis:
    git: git://github.com/denniskaselow/dartemis.git
dev_dependencies:
  box2d: any
  vector_math: '>=0.9.7'
  unittest: any
