name: dartemis_addons
version: 0.1.0-dev
author: david bernard
description: A set of addons (Component, System, helper, ...) usable with dartemis
homepage: https://github.com/davidB/dartemis_addons
documentation: https://github.com/davidB/dartemis_addons
dev_dependencies:
  dartemis: '>=0.4.1'
  unittest: any
  vector_math: '>=0.9.7'
  simple_audio:
    git: git://github.com/johnmccutchan/simpleaudio.git
  web_ui: any
#environment:
#    sdk: 0.4.5+1.r21094
#    path: ../dartemis
#  box2d: any
#  vector_math: '>=0.9.7'
