name: dartemis_toolbox
version: 0.5.0-dev
author: david bernard <david.bernard.31@gmail.com>
description: 'A set of libraries for game developpement : easing function, colors,
  particles, collisions, verlet physics, addons for dartemis, ...'
homepage: http://davidb.github.io/dartemis_toolbox/
documentation: http://davidb.github.io/dartemis_toolbox/apidoc/
environment:
  sdk: ">=1.0.0 <2.0.0"
dev_dependencies:
  dartemis: '>=0.6.0'
  simple_audio:
    git: git://github.com/johnmccutchan/simpleaudio.git
    version: '>=0.9.0'
  unittest: any
  vector_math: any
  web_ui: '>=0.4.8+1'
  html_toolbox:
    git: https://github.com/davidB/html_toolbox
